quarkus.http.port=8081

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
mp.messaging.incoming.transactions-in.connector=smallrye-kafka
mp.messaging.incoming.transactions-in.topic=transaction.requested.v1
mp.messaging.incoming.transactions-in.group.id=fraud-service
mp.messaging.incoming.transactions-in.auto.offset.reset=earliest
mp.messaging.incoming.transactions-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

mp.messaging.outgoing.fraud-out.connector=smallrye-kafka
mp.messaging.outgoing.fraud-out.topic=fraud.decision.v1
mp.messaging.outgoing.fraud-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.fraud-out.acks=all

quarkus.smallrye-openapi.info-title=LedgerGuard Fraud API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Explainable rule-based transaction risk evaluation
quarkus.swagger-ui.always-include=true

quarkus.otel.sdk.disabled=${OTEL_DISABLED:true}
quarkus.micrometer.export.prometheus.enabled=true
